artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://github.com/lakiet1609/project3/releases/download/dataset/train.zip'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/tomato


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5